DROP TABLE IF EXISTS actor;
CREATE TABLE actor (
    id SERIAL PRIMARY KEY,
    first_name CHARACTER VARYING(45) NOT NULL,
    last_name CHARACTER VARYING(45) NOT NULL,
    last_update TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);
